### ISSUE TITLE
[bug] vk/kick command does not work

### ISSUE THREAD

**Issue by Philian73** [gregzaal/Auto-Voice-Channels#60] opened 2020-08-20 01:48 UTC
Bot refuses to kick people by voting.
Nothing happens, no matter how much time has passed and no matter how many people put the state emoji.
[screen](https://prnt.sc/u2jwwk)

**Comment by gregzaal** [comment] 2020-08-20 07:30
Duplicate of #34

**Closed by gregzaal** 2020-08-20 07:30 UTC
